service: kvsTranscribeTable
frameworkVersion: "3"

provider:
  name: aws
  runtime: nodejs16.x
  # profile: mark-helsby-aws
  profile: tejas-sa-iam

resources: # CloudFormation template syntax from here on.
  Resources:
    usersTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: contactDetails
        AttributeDefinitions:
          - AttributeName: contactId
            AttributeType: S
        KeySchema:
          - AttributeName: contactId
            KeyType: HASH
        # assuming 5 concurrent calls
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
